version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "3306:3306"
    networks:
      - laravel

  vue:
    image: node:14
    container_name: vue-app
    restart: unless-stopped
    working_dir: /var/www/vue
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - ./path/to/your/vue/app:/var/www/vue
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
